"""add meta attribution field to new_students

Revision ID: 5d96e5442966
Revises: 6a1f3a7fe458
Create Date: 2026-08-15 19:38:07.436073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d96e5442966'
down_revision: Union[str, None] = '6a1f3a7fe458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_students', sa.Column('meta', sa.JSON(), nullable=True, comment='Lead attribution, e.g. {"source": "meta"|"google"|"organic"}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_students', 'meta')
    # ### end Alembic commands ###
