"""add status field to teachers and students

Revision ID: f3c9a4d7b210
Revises: a8e416d0e88a
Create Date: 2026-08-17 00:00:00.000000

Replaces `teachers.resigned`/`resigned_at` and `students.is_active` with a
single `status` column per table (NOT NULL, default 'active'), plus a
`status_changed_at` timestamp, so a third "frozen" state can be represented
without a second boolean. Values:
  - teachers.status:  'active' | 'resigned' | 'frozen'
  - students.status:  'active' | 'inactive' | 'frozen'

Hand-written (not autogenerated).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c9a4d7b210'
down_revision: Union[str, None] = 'a8e416d0e88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- teachers ---
    op.add_column(
        'teachers',
        sa.Column('status', sa.Text(), nullable=False, server_default='active', comment="'active', 'resigned', or 'frozen'"),
    )
    op.add_column('teachers', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE teachers SET status = 'resigned', status_changed_at = resigned_at WHERE resigned IS TRUE")
    op.drop_index('idx_teachers_resigned', table_name='teachers')
    op.create_index(
        'idx_teachers_status_active', 'teachers', ['status'], postgresql_where=sa.text("status = 'active'::text")
    )
    op.drop_column('teachers', 'resigned')
    op.drop_column('teachers', 'resigned_at')

    # --- students ---
    op.add_column(
        'students',
        sa.Column('status', sa.Text(), nullable=False, server_default='active', comment="'active', 'inactive', or 'frozen'"),
    )
    op.add_column('students', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE students SET status = 'inactive' WHERE is_active IS FALSE")
    op.drop_index('idx_students_active', table_name='students')
    op.create_index(
        'idx_students_status_active', 'students', ['status'], postgresql_where=sa.text("status = 'active'::text")
    )
    op.drop_column('students', 'is_active')


def downgrade() -> None:
    # --- students ---
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE students SET is_active = (status != 'inactive')")
    op.drop_index('idx_students_status_active', table_name='students')
    op.create_index('idx_students_active', 'students', ['is_active'], postgresql_where=sa.text('is_active = true'))
    op.drop_column('students', 'status_changed_at')
    op.drop_column('students', 'status')

    # --- teachers ---
    op.add_column('teachers', sa.Column('resigned', sa.Boolean(), nullable=True))
    op.add_column('teachers', sa.Column('resigned_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(
        "UPDATE teachers SET resigned = (status = 'resigned'), "
        "resigned_at = CASE WHEN status = 'resigned' THEN status_changed_at ELSE NULL END"
    )
    # NOTE: downgrade is lossy for the 'frozen' status — frozen teachers/students
    # collapse back to active (resigned=false / is_active=true) since the old
    # schema has no third state. This is expected and acceptable; downgrades are
    # an emergency-only path.
    op.drop_index('idx_teachers_status_active', table_name='teachers')
    op.create_index('idx_teachers_resigned', 'teachers', ['resigned'], postgresql_where=sa.text('resigned = false'))
    op.drop_column('teachers', 'status_changed_at')
    op.drop_column('teachers', 'status')
