import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext';
import ProtectedRoute from '../components/ProtectedRoute';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const protectedPaths = ['/min-side', '/profil', '/admin']; // Add paths that require authentication

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {protectedPaths.includes(location.pathname) ? (
            <ProtectedRoute>{children}</ProtectedRoute>
          ) : (
            children
          )}
        </AuthProvider>
      </body>
    </html>
  );
}